# action.yml
name: 'Telegram File Uploader'
description: 'Uploader your GitHub action files to Telegram via Telethon'
inputs:
  to-who:
    description: 'Send to who'
    required: true
  message:
    description: 'Message'
    required: true
  files:
    description: 'Files (one file per line)'
    required: true
outputs:
  message_url:
    description: 'URL of the first uploaded message'
  message_urls:
    description: 'Comma-separated URLs of all uploaded messages'
  message_id:
    description: 'ID of the first uploaded message'
  message_ids:
    description: 'Comma-separated IDs of all uploaded messages'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--to=${{ inputs.to-who }}"
    - "--message=${{ inputs.message }}"
    - "--files=${{ inputs.files }}"
branding:
  icon: 'upload-cloud'
  color: 'green'
